### ISSUE TITLE
Support for fastify 4

### ISSUE THREAD

**Issue by AWare** [fastify/fastify-funky#117]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

For fastify funky to support fastify 4.

### Motivation

It's the current version of fastify.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
unsure, it might require some updates too.
