### ISSUE TITLE
Package name incorrect in README

### ISSUE THREAD

**Issue by AWare** [fastify/fastify-funky#96]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The package README still refers to this package as `fastify-funky` instead of `@fastify/funky`

**Comment by Fdawgs** [comment]
See the Work To Be Done section in https://github.com/fastify/fastify/issues/3733#issuecomment-1111188683

**Comment by AWare** [comment]
Sorry, but this should have been done before deprecating the original modules.
